package com.example.qrcodesample11.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.qrcodesample1.mycircle.greendao.MyCircleBeanTable;

import com.example.qrcodesample11.database.MyCircleBeanTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myCircleBeanTableDaoConfig;

    private final MyCircleBeanTableDao myCircleBeanTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myCircleBeanTableDaoConfig = daoConfigMap.get(MyCircleBeanTableDao.class).clone();
        myCircleBeanTableDaoConfig.initIdentityScope(type);

        myCircleBeanTableDao = new MyCircleBeanTableDao(myCircleBeanTableDaoConfig, this);

        registerDao(MyCircleBeanTable.class, myCircleBeanTableDao);
    }
    
    public void clear() {
        myCircleBeanTableDaoConfig.clearIdentityScope();
    }

    public MyCircleBeanTableDao getMyCircleBeanTableDao() {
        return myCircleBeanTableDao;
    }

}
